config/routes.rb
Rails.application.routes.draw do

  resources :owners
  get '/' => 'sessions#welcome'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  post '/signout' => 'sessions#destroy'
  get '/signup' => 'agents#new'
  get '/auth/facebook/callback' => 'sessions#create_with_facebook'
  get '/leads/:id/next', to: 'leads#next'

  resources :agents, only: [:show] do
    resources :leads, only: [:new, :edit, :show, :index]
    resources :regions, only: [:show]
    resources :industries, only: [:show]
  end

  resources :leads do
    resources :owners
  end

  resources :industries
  resources :regions
  resources :leads
  resources :agents
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agent.rb
class Agent < ApplicationRecord
  has_secure_password
  #belongs_to :region, optional: true
  belongs_to :region
  has_many :leads
  has_many :industries, through: :leads
  accepts_nested_attributes_for :region, reject_if: proc { |attributes| attributes['name'].blank? }
  #validates :name, uniqueness: true
  validates :password, presence: true
  validates :name, presence: true

end

app/models/lead.rb
class Lead < ApplicationRecord
  belongs_to :agent
  belongs_to :industry
  belongs_to :region
  has_many :owners
  accepts_nested_attributes_for :industry, reject_if: proc { |attributes| attributes['name'].blank? }
  validates :name, presence: true
  validates :booked_loans, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def next(lead_id, agent_id)
    #binding.pry
    nextlead = Lead.where("id > ?",lead_id).where("agent_id =?", agent_id).first
    if nextlead
      nextlead
    else
      Lead.where("agent_id =?", agent_id).first
    end
  end

  def self.by_agent(agent_id, status)
    self.where("status = ?", status).where("agent_id = ?", agent_id)
  end

  def self.by_region(region_id, status)
    self.where("status = ?", status).where("region_id = ?", region_id)
  end

  def self.by_industry(industry_id, status)
    self.where("status = ?", status).where("industry_id = ?", industry_id)
  end

  def self.by_manager_region(region_id)
    self.where("region_id = ?", region_id)
  end

  def self.by_manager_industry(industry_id)
    self.where("industry_id = ?", industry_id)
  end


end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

  def new
    #binding.pry
    agent_check
    @agent = current_user
    @lead = Lead.new
    @region = @agent.region
    #redirect_to new_agent_lead_path(@agent)
  end

  def create
    @lead = Lead.create(leads_params)
    #binding.pry
    if @lead.errors.any?
      @region = current_user.region
      render :new
    else
      @lead.save
      redirect_to lead_path(@lead)
    end
  end

  def edit
    #binding.pry
    control_check
    @lead = Lead.find_by(id: params[:id])
  end

  def update
    @lead = Lead.find(params[:id])
    @lead.update(leads_params)
    if @lead.errors.any?
      render :edit
    else
      redirect_to lead_path(@lead)
    end
  end

  def show
    #binding.pry

    control_check
    if Lead.find_by(id: params[:id])
      #binding.pry
      @lead = Lead.find_by(id: params[:id])
      @agent = @lead.agent
      @owners = @lead.owners
      #@owner = @lead.owners.build
      @owner = Owner.new
    end
    @leads = current_user.leads
    @lead_ids = []
    #binding.pry
    @leads.each do |lead|
       @lead_ids << lead[:id]
    end
    #binding.pry
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @lead, status: 200}
    end
  end

  def next
    #binding.pry
    @lead = Lead.find_by(id: params[:id])
    @next_lead = @lead.next(params[:id], @lead.agent.id)
    render json: @next_lead
  end

  def destroy
    #binding.pry
    @lead = Lead.find(params[:id])
    @lead.destroy
    @agent = Agent.find(session[:agent_id])
    redirect_to agent_path(@agent)
  end

  def index
    #binding.pry
    agent_check
    @agent = current_user
    if params[:status].nil? || params[:status] == ""
      @leads = @agent.leads
    else
      @leads = Lead.by_agent(@agent.id, params[:status])
    end
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @leads}
    end
  end


  private
  def leads_params
    params.require(:lead).permit(:name, :status, :agent_id, :region_id, :booked_loans, :industry_id, industry_attributes:[:name])
  end

  def control_check
    if !logged_in?
      flash[:notice] = "Agent not logged in"
      redirect_to '/'
    elsif !lead_exists?
      flash[:notice] = "Lead doesn't exist"
      redirect_to agent_path(session[:agent_id])
    elsif agent_is_not_current_user?
      flash[:notice] = "Agent is not current user or agent doesn't exist"
      redirect_to agent_path(session[:agent_id])
    elsif lead_does_not_belong_to_agent?
      flash[:notice] = "Lead does not belong to current agent"
      redirect_to agent_path(session[:agent_id])
    end
  end

  def lead_exists?
    #binding.pry
    if !params[:id].nil?
      Lead.find_by(id: params[:id]) != nil
    end
  end

  def agent_is_not_current_user?
    if !params[:agent_id].nil?
      Agent.find_by(id: params[:agent_id]) != current_user
    end
  end

  def lead_does_not_belong_to_agent?
    if !params[:id].nil? && Lead.find_by(id: params[:id])
      Lead.find_by(id: params[:id]).agent != current_user
    end
  end


end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/leads/edit.html.erb
<div class = "container">
  <div class = "row">
    <h2>Edit a Lead</h2>
  </div>

  <div class = "row">
    <br>
    <%= form_for @lead do |f| %>
      <label>Name:</label>
      <%= f.text_field :name %><br>
      <%= f.hidden_field :agent_id, value: session[:agent_id] %>
      <%= f.hidden_field :region_id, value: @lead.region_id %>
      <label>Create Industry:</label>
      <%= f.fields_for :industry, @lead.build_industry do |industry_fields| %>
        <%= industry_fields.text_field :name %>
      <% end %>
      <label>(Or) Select Industry: </label>
      <%= f.collection_select  :industry_id, Industry.all, :id, :name, {:selected => @lead.industry_id} %><br>
      <label>Status: </label>
      <%= f.select(:status ,options_for_select([['Go','Go'],['No Go','No Go'],['Converted','Converted']],'GO')) %><br>
      <label>Booked loan amount $:</label>
      <%= f.text_field :booked_loans %><br><br>
      <%= f.submit %>
    <% end %>
  </div>

  <div class = "row">
    <br><br>
    <%= render partial: "agents/error", locals: {variable: @lead} %>
  </div>

</div>

app/views/leads/index.html.erb
<div class = "container">
  <div class = "row">
    <h2> Leads Index </h2>
  </div>

  <div class = "row">
    <br>
    <%= link_to "Back to Profile", agent_path(@agent) %><br>
    <br>
  </div>

  <div class = "row">
    <%= form_tag("/agents/#{@agent.id}/leads", method: "get") do %>
      <%= select_tag(:status ,options_for_select([['Go','Go'],['No Go','No Go'],['Converted','Converted']]),include_blank: true) %>
      <%= submit_tag "Filter by Status" %>
    <% end %>
  </div>

  <div class = "row">
    <br>
    <table class="table">
      <tr>
        <th>ID no</th>
        <th>Industry</th>
        <th>Lead Name</th>
        <th>Status</th>
        <th>Booked Amount</th>
      </tr>
      <% @leads.each do |lead| %>
      <tr>
          <td><%= lead.id %></td>
          <td><%= link_to lead.industry.name, industry_path(lead.industry) %></td>
          <td><%= link_to lead.name, lead_path(lead) %></td>
          <td><%= lead.status %></td>
          <td><%= lead.booked_loans %></td>
      </tr>
      <% end %>
    </table>
  </div>

  <!--<div class = "js_leads_index">
  </div>-->

</div>

app/views/leads/new.html.erb
<div class = "container">
  <div class = "row">
    <h2>Create a Lead</h2>
  </div>

  <div class = "row">
    <%= form_for @lead do |f| %>
      <label>Name:</label>
      <%= f.text_field :name %><br>
      <%= f.hidden_field :agent_id, value: session[:agent_id] %>
      <%= f.hidden_field :region_id, value: @region.id  %>
      <label>Create Industry:</label>
      <%= f.fields_for :industry, @lead.build_industry do |industry_fields| %>
        <%= industry_fields.text_field :name %>
      <% end %>
      <label>(Or) Select Industry: </label>
      <%= f.collection_select  :industry_id, Industry.all, :id, :name %><br>
      <label>Status: </label>
      <%= f.select(:status ,options_for_select([['Go','Go'],['No Go','No Go'],['Converted','Converted']],'GO')) %><br>
      <%= f.submit %>
    <% end %>
  </div>

  <div class = "row">
    <br><br>
    <%= render partial: "agents/error", locals: {variable: @lead} %>
  </div>
</div>

app/views/leads/show.html.erb
<div class = "container">

  <div class ="row">
    <h2>Your Lead:</h2>
  </div>

  <!--<a href="#" class="js-next" lead-id="<%=@lead.id%>" lead-ids="<%=@lead_ids%>">Next Lead</a>-->


  <div class ="row">
    <h4 id="leadName"><strong>Lead Name: </strong><%= @lead.name %></h4>
    <h4 id="industryName"><strong>Industry: </strong><%= @lead.industry.name %></h4>
    <h4 id="leadStatus"><strong>Status: </strong><%= @lead.status %></h4>
    <% if @lead.status == "Converted" %>
      <h4 id="bookedAmount"><strong>Booked amount($): </strong><%= @lead.booked_loans %></h4>
    <% end %>
  </div>

  <div class="owners">
    <h4>Owners:</h4>
    <ol id="ownerlist">
      <% @owners.each do |owner| %>
      <li id="ownerName"><%= owner.name %></li>
      <% end %>
    </ol>
    <ol id="ownerlist2">
    </ol>
  </div>

  <!--<%= form_for(@owner, :url => owners_path(@lead)) do |f| %>
  <% end %>-->
  <%= form_for(@owner, :url => lead_owners_path(@lead)) do |f| %>
    <%= f.text_field :name %><br>
    <p><%= f.submit %></p>
  <% end %>

  <div class ="sort">
    <a id="sort" href= "<%=lead_path(@lead) %>">Sort</a>
  </div>

  <div class ="row">

    <p><%= form_tag edit_lead_path(@lead), method: "get" do %>
        <%= submit_tag("Edit Lead") %>
      <% end %>
    </p>

    <p><%= form_tag lead_path(@lead), method: "delete" do %>
        <%= submit_tag("Delete Lead") %>
      <% end %>
    </p>
    <%= link_to "Back to Profile", agent_path(@agent) %>
  </div>

  <div class="row">
    <a href="#" class="js-index">All leads</a>
  </div>
  <div class="row" id="leads">
  </div>

</div>