config/routes.rb
Rails.application.routes.draw do

  resources :owners
  get '/' => 'sessions#welcome'
  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  post '/signout' => 'sessions#destroy'
  get '/signup' => 'agents#new'
  get '/auth/facebook/callback' => 'sessions#create_with_facebook'
  get '/leads/:id/next', to: 'leads#next'

  resources :agents, only: [:show] do
    resources :leads, only: [:new, :edit, :show, :index]
    resources :regions, only: [:show]
    resources :industries, only: [:show]
  end

  resources :leads do
    resources :owners
  end

  resources :industries
  resources :regions
  resources :leads
  resources :agents
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agent.rb
class Agent < ApplicationRecord
  has_secure_password
  #belongs_to :region, optional: true
  belongs_to :region
  has_many :leads
  has_many :industries, through: :leads
  accepts_nested_attributes_for :region, reject_if: proc { |attributes| attributes['name'].blank? }
  #validates :name, uniqueness: true
  validates :password, presence: true
  validates :name, presence: true

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController

  def new
    @agent = Agent.new
  end

  def create
    #binding.pry
    @agent = Agent.create(agent_params)
    if !@agent.errors.empty?
      #binding.pry
      render :new
    else
      set_session
    end
  end

  def edit
    agent_check
    @agent = Agent.find(params[:id])
  end

  def update
    @agent = Agent.find(params[:id])
    @agent.update(agent_params)
    if @agent.errors.any?
      render :edit
    else
      redirect_to agent_path(@agent)
    end
  end

  def show
    agent_check
    @agent = current_user
    @total_leads = @agent.leads.count
    @total_go = @agent.leads.where(status: "Go").count
    @total_nogo = @agent.leads.where(status: "No Go").count
    @total_converted = @agent.leads.where(status: "Converted").count
    @total_booked = @agent.leads.sum(:booked_loans)
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @agent}
    end
  end

  def index
    #binding.pry
    agent_check
    @agent = Agent.find_by(id: session[:agent_id])
    if @agent.manager
      @agents = Agent.where("region_id = ?", @agent.region_id)
      @total_leads = Lead.where("region_id = ?", @agent.region_id).count
      @total_go = Lead.where("region_id = ?", @agent.region_id).where("status = ?","Go").count
      @total_nogo = Lead.where("region_id = ?", @agent.region_id).where("status = ?","No Go").count
      @total_converted = Lead.where("region_id = ?", @agent.region_id).where("status = ?","Converted").count
      @total_booked = Lead.where("region_id = ?", @agent.region_id).sum(:booked_loans)
    else
      redirect_to agent_path(@agent)
    end
  end


  private
  def agent_params
    params.require(:agent).permit(:name, :password, :manager, :region_id, region_attributes:[:name])
  end


end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/views/agents/_error.html.erb
<% if variable.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4>
      <%= pluralize(variable.errors.count, "error") %>
      prohibited this article from being saved:
    </h4>

    <ul>
    <% variable.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    <p> Please correct the concerned fields. </p>
  </div>
<% end %>

app/views/agents/_form.html.erb
<%= form_for @agent do |f| %>
  <label>Name:</label>
  <%= f.text_field :name %><br>
  <label>Password:</label>
  <%= f.password_field :password %><br>
  <label>Manager:</label>
  <%= f.check_box :manager %><br>
  <label>Create Region:</label>
  <%= f.fields_for :region, @agent.build_region do |region_fields| %>
    <%= region_fields.text_field :name %>
  <% end %>
  <label>(Or) Select a Region</label>
  <%= f.collection_select :region_id, Region.all, :id, :name, :prompt => true %><br>
  <%= f.submit %>
<% end %>

app/views/agents/edit.html.erb
<div class = "container">
  <div class = "row">
    <h2>Edit Agent Details</h2>
  </div>

  <div class = "row">
    <br>
    <%= render 'form' %>
  </div>

  <div class = "row">
    <br><br>
    <%= render partial: "error", locals: {variable: @agent} %>
  </div>
</div>

app/views/agents/index.html.erb
<div class = "container">
  <div class = "row">
    <h2>Agents Index</h2>
  </div>

  <div class = "row">
    <br>
    <%= link_to "Back to Profile", agent_path(session[:agent_id]) %><br>
    <br>
  </div>

  <div class ="row">
    <h4>All Agents</h4>
    <table class="table">
      <tr>
        <th>Total Leads</th>
        <th>Total Go</th>
        <th>Total No Go</th>
        <th>Total Converted</th>
        <th>Total Booked Loans</th>
      </tr>
      <tr>
          <td><%= @total_leads %></td>
          <td><%= @total_go %></td>
          <td><%= @total_nogo %></td>
          <td><%= @total_converted %></td>
          <td><%= @total_booked %></td>
      </tr>
    </table>
    <br><br>
  </div>

  <div class = "row">
    <h4>Per Agent</h4>
    <table class="table">
      <tr>
        <th>ID no</th>
        <th>Name</th>
        <th>Total Leads</th>
        <th>Total Go</th>
        <th>Total No Go</th>
        <th>Total Converted</th>
        <th>Booked Amount</th>
      </tr>
      <% @agents.each do |agent| %>
      <tr>
          <td><%= agent.id %></td>
          <td><%= agent.name %></td>
          <td><%= agent.leads.count %></td>
          <td><%= agent.leads.where(status: "Go").count %></td>
          <td><%= agent.leads.where(status: "No Go").count %></td>
          <td><%= agent.leads.where(status: "Converted").count %></td>
          <td><%= agent.leads.sum(:booked_loans) %></td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/agents/new.html.erb
<div class = "container">

  <div class = "row">
    <h2>Create an Agent:</h2>
  </div>

  <div class = "row">
    <br>
    <%= render 'form' %>
  </div>


  <div class = "row">
    <br><br>
    <%= render partial: "error", locals: {variable: @agent} %>
  </div>

</div>

app/views/agents/show.html.erb
<div class = "container">

  <div class = "row">
    <h2>Hi! <%= @agent.name %></h2>
  </div>


  <div class = "row">
    <h3>Your Region: <%= link_to @agent.region.name, region_path(@agent.region) %></h3>
  </div>

  <div class = "row">
    <br>
    <span><%= link_to "Create Lead" , new_agent_lead_path(@agent) %></span>&nbsp;&nbsp;&nbsp;
    <span><%=link_to "Your Leads" , leads_path, class: "leads_index" %></span>
    <br>
  </div>

  <div class = "row">
    <br>
    <% if @agent.manager %>
      <span><%=link_to "Your Agents", agents_path %>&nbsp;&nbsp;&nbsp;<%=link_to "Industries Summary", industries_path %>&nbsp;&nbsp;&nbsp;<%= link_to "Regions Summary", regions_path %></span>
    <% end %>
    <br><br>
  </div>

  <div class = "row">
    <table id = "lead_table" class="table">
      <tr>
        <th>Total Leads</th>
        <th>Total Go</th>
        <th>Total No Go</th>
        <th>Total Converted</th>
        <th>Total Booked Loans</th>
      </tr>
      <tr>
        <td><%= @total_leads %></td>
        <td><%= @total_go %></td>
        <td><%= @total_nogo %></td>
        <td><%= @total_converted %></td>
        <td><%= @total_booked %></td>
      </tr>
    </table>
  </div>

  <div class = "js_leads_index">
    <table id="js_leads_index_table" class="table">
    </table>

  </div>

  <div class = "row">
    <p><%= form_tag edit_agent_path(@agent), method: "get" do %>
        <%= submit_tag("Edit Agent") %>
      <% end %>
    </p>
    <p><%= form_tag signout_path do %>
      <input type=submit value='Sign Out'>
    <% end %>
    </p>
  </div>


  <div class = "row">
    <% if flash[:notice] %>
      <div class="alert alert-danger" role="alert"><%= flash[:notice] %></div>
    <% end %>
  </div>

</div>